FIX: Build on travis
Build fails because of:

    $ pip install --upgrade pip
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.7-dev/bin/pip", line 6, in <module>
        from pip._internal.cli.main import main
    ModuleNotFoundError: No module named 'pip'

This is nice opportunity to update some things
to Python 3.8.